<div class="header">
	<h1 class="titre"><img src="https://media.giphy.com/media/adHIq5Pw9oNxK/source.gif" style="
    width: 70px;" alt="">Virtual Coffee</h1>
	<a href="http://localhost/developpement/tchat/?page=messages" class="navbar">messages</a>
	<a href="http://localhost/developpement/tchat/?page=logout" class="navbar">log out</a>
</div>
<div class="welcome"><p>Bienvenue, <strong><?=$_SESSION['login']?></strong>.</p>
</div>

