<div class="header">
	<h1 class="titre">HEADER</h1>
	<a href="http://localhost/developpement/15-blog/?page=articles" class="navbar">articles</a>
	<a href="http://localhost/developpement/15-blog/?page=create_article" class="navbar">create article</a>
	<a href="http://localhost/developpement/15-blog/?page=logout" class="navbar">log out</a>
</div>
<div class="welcome"><p>Bienvenue, <strong><?=$_SESSION['login']?></strong>.</p>
</div>