<h1>HEADER DE OUUUUUUFFF</h1>
<nav class="navbar-inverse">
				<div class="container-fluid">
					<ul class="nav navbar-nav">
						<li> <a href="http://localhost/developpement/blog/index.php?page=logout">LOGOUT</a> </li>
						<li> <a href="http://localhost/developpement/blog/index.php?page=articles">ARTICLES</a> </li>
						<li> <a href=><?=htmlentities($_SESSION['login'])?></a> </li>
					</ul>
					<form class="navbar-form navbar-right" method="">
						<input type="text" class="input-sm form-control" placeholder="Recherche moi !">
						<button type="submit" class="btn btn-primary btn-sm">
							<span class="glyphicon glyphicon-eye-open"></span> Recherche
						</button>
					</form>
				</div>
			</nav>