<div class="container">
<br><br>
  <form class="form-horizontal" method="post">
    <input type="hidden" name="action" value="login">
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Pseudo</label>
      <div class="col-sm-10">
        <input name="login" type="text" class="form-control" id="inputEmail3" placeholder="pseudo">
      </div>
    </div>
    <div class="form-group">
      <label for="inputPassword3" class="col-sm-2 control-label">Mot de passe</label>
      <div class="col-sm-10">
        <input name="password" type="password" class="form-control" id="inputPassword3" placeholder="Password">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <div class="checkbox">
          <label>
            <input type="checkbox"> Se souvenir
          </label>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">Se connecter</button>
      </div>
    </div>
  </form>

</div>