<div class="container">

		<div class="messages js_msg_list">

			<?php require('apps/message_elem.php'); ?>
			

		</div>

	
		<div class="users">
			<ul>
				<li><div class="avatar-small"></div><?php //htmlentities($message['id'])?></li>
			</ul>
		</div>
			<?php  require('views/create_message.phtml'); ?>
		
	
	</div>

	<script>
	setInterval(function()
	{
		$('.js_msg_list').load('index.php?page=message_elem&ajax');
	}, 500);
	</script>