<div class="container">

		<div class="messages">

			<div class="posted-message">
				<div class="avatar"></div>
				<h5><span>Machin</span> a dit à <span>00h00</span>:</h5>
				<p>hé salut !</p>
			</div>
			<div class="posted-message">
				<div class="avatar"></div>
				<h5><span>Machin2</span> a dit à <span>00h00</span>:</h5>
				<p>hé salut ! Lorem ipsum dolor sit amet, consectetur adipisicing elit.
			</div>

		</div>

	
		<div class="users">
			<ul>
				<li><div class="avatar-small"></div>Jerem$tar</li>
			</ul>
		</div>

		<div class="chat-input">
			<form action="POST">
				<textarea name="message" id="" cols="30" rows="9" placeholder="Tapez votre message ici"></textarea><button>ENVOYER</button>
			</form>	
		</div>
	</div>