<div class="container">

		<div class="messages">

			<div class="posted-message">
				<div class="avatar"></div>
				<h5><span><?=htmlentities($message['login'])?></span> a dit à <span><?=$message['date']?></span>:</h5>
				<p><?=htmlentities($message['content'])?></p>
			</div>

		</div>

	
		<div class="users">
			<ul>
				<li><div class="avatar-small"></div><?=htmlentities($message['login'])?></li>
			</ul>
		</div>

		<div class="chat-input">
			<form action="POST">
				<textarea name="message" id="" cols="30" rows="9" placeholder="Tapez votre message ici"></textarea><button>ENVOYER</button>
			</form>	
		</div>
	</div>