<div class="container">

<form class="form-horizontal" method="post">
  <input type="hidden" name="action" value="register">
  <div class="form-group">
    <br><br>
    <label for="inputEmail3" class="col-sm-2 control-label">Pseudo</label>
    <div class="col-sm-10">
      <input name="login" type="text" class="form-control" id="inputEmail3" placeholder="Pseudo">
    </div>
  </div>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <input name="email" type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Mot de passe</label>
    <div class="col-sm-10">
      <input  name="password" type="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
  </div>
  <div class="form-group">
    <label for="date" class="col-sm-2 control-label">Date de naissance</label>
    <div class="col-sm-10">
      <input  name="date" type="date" class="form-control" id="date" placeholder="votre date">
    </div>
  </div>
   <label for="inputEmail3" class="col-sm-2 control-label">Url de l'avatar</label>
    <div class="col-sm-10">
      <input name="avatar" type="url" class="form-control" id="avatar" placeholder="http://">
    </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">S'inscrire</button>
    </div>
  </div>
</form>

</div>