<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>MVC</title>
		<style>
	.navbar-nav{
		text-align: center;
	}
	.container{
		text-align: center;
	}

	.tache{
		border: 1px solid black;
		width: 600px;
		margin: auto;
		margin-top: 10px;
		word-wrap: break-word;
		padding: 10px;

	}

	.priority_1
	{
		color:red;
	}
	.priority_2
	{
		color:orange;
	}
	.priority_3
	{
		color:green;
	}
	body{
		text-align: center;
	}
	input, label, select, textarea{
		display: inline-block;
		margin: 20px 0px;
		vertical-align: top;
		margin-top: 10px;
	}
	.form-horizontal{
		text-align: center;
		width: 600px;
		margin:auto;
		padding-top: 50px;
	}
	.thumbnail {
    padding:0px;
}
.panel {
	position:relative;
}
.panel>.panel-heading:after,.panel>.panel-heading:before{
	position:absolute;
	top:11px;left:-16px;
	right:100%;
	width:0;
	height:0;
	display:block;
	content:" ";
	border-color:transparent;
	border-style:solid solid outset;
	pointer-events:none;
}
.panel>.panel-heading:after{
	border-width:7px;
	border-right-color:#f7f7f7;
	margin-top:1px;
	margin-left:2px;
}
.panel>.panel-heading:before{
	border-right-color:#ddd;
	border-width:8px;
}

	</style>
	<link rel="stylesheet" href="css/bootstrap.min.css">
</head>
<body>
	<?php require('apps/header.php'); ?>
	<?php require('apps/container.php'); ?>
	<?php require('apps/footer.php'); ?>
</body>
</html>