<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>CHAT</title>
		<style>

		/*HEADER*/
			h1{
				font-size: 50px;
				display: inline-block;


			}

			h5{
				text-transform: uppercase;
				font-weight: normal;
				font-size: 12px;
				letter-spacing: 1px;
				
			}

			h2{
				color: #D32222;

			}
			.welcome{
				float: right;
				color: #D32222;
				margin-top: -70px;
				margin-right: 15px;
				font-size: 12px;
			}
			article:not(.row){
				border: 1px solid #EEE;
				padding: 15px;
			}
			.article-list{
				border: 1px solid #EEE;
				padding: 15px;
				margin-top: 25px;
			}
			.container{
				width:1000px;
				margin: 0 auto;
			}
			.login input{
				border: 1px solid #EEE;
				padding: 5px;
				margin-bottom: 5px;
			}
			.register input{
				border: 1px solid #EEE;
				padding: 5px;
				margin-bottom: 15px;
				width: 100%;
			}
			
			.navbar{
				float: right;
			}

			a.navbar{
				margin-right: 15px;
				color: grey;
				text-transform: uppercase;
				text-decoration: none;
				letter-spacing: 1px;
			}

			a.navbar:hover{
				color:#D32222;
			}

			.header{
				height:90px;
				width:750px;
				margin: 0 auto;
			}

			.titre{
				float: left;
				clear: both;
				margin:0;
				display: inline-block;
				vertical-align: middle;
				
			}


		/*CHAT*/

		*{
	box-sizing: border-box;

		}

		img{
			max-width: 100%;
		}
		body{
			font-family: sans-serif;

		}

		.container{
			width:700px;
			height: 700px;
			margin: 0 auto;
			transition: all 1s ease;
		}

		.messages{
			width:550px;
			float: left;
			height: 492px;
			border: 1px solid #EEE;
			padding: 15px;
			overflow: auto;
		}
		.avatar{
			height: 50px;
			width:50px;
			border-radius: 50px;
			background-color: #EEE;
			float: left;
			margin-right: 10px;
		}

		.avatar-small{
			height: 20px;
			width:20px;
			border-radius: 50px;
			margin-right: 10px;
			background-color: #FFF;
			float: left;
		}



		.users{
			width:150px;
			height: 700px;
			float: right;
			background-color: #EEE;
			padding: 15px;
		}

		.user{
			float: left;

		}
		ul{
			padding:0px;
		}

		li{
			list-style: none;
		}

		textarea{
			width:550px;
			padding:10px;
			font-family: sans-serif;
		}

		button{
			width:550px;
			background-color: #D32222;
			border: 0px;
			padding: 16px;
			color: #FFF;

		}

		button:hover{
			
			background-color: #49250C;
			color: #FFF;

		}

		p{
			margin-top: -15px;
			word-wrap: break-word;
		}

		span{
			font-weight: bold;
		}


	</style>
	<link rel="stylesheet" href="css/bootstrap.min.css">
</head>
<body>
	<?php require('apps/header.php'); ?>
	<?php require('apps/container.php'); ?>
	<!-- <?php require('apps/footer.php'); ?> -->
</body>
</html>